version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
