FROM node:18-alpine

WORKDIR /app

# Copy package.json from cronWorker/
COPY package*.json ./  
RUN npm install --omit=dev  

COPY ./utils /app/utils  
COPY ./cleanup /app/cleanup  


# Run the cleanup job
CMD ["node", "/app/cleanup/cleanupJob.js"]
