name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-backend ./server

      - name: Push to Render (Trigger Deployment)
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}"
